/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica2;

/**
 *
 * @author Luisda
 */
public class PantallaJuego extends javax.swing.JFrame {

    public static String DatosPantallaCulebra[][] = new String[10][10];  // [X][Y]

    public static int Num;
    
    public static String RelojParaReporte;
    
    public static String Movimientos="<br>";

    public static void PonerTexto(String TextoReloj) {
        Reloj.setText(TextoReloj);
    }

    public static String TextoParaPantalla(String[][] DisCul) {
        String Texto = "<html><body><tt>";
        int como;
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                Texto = Texto + DisCul[j][i];
            }
            Texto = Texto + "<br>";
        }
        Texto = Texto + "</body></html>";
        return Texto;
    }
    public static String TextoParaPantalla2(String[][] DisCul) {
        String Texto = "<html><body><font size=\"6\"><tt>";
        int como;
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                Texto = Texto + DisCul[j][i];
            }
            Texto = Texto + "<br>";
        }
            Texto = Texto + "<font size=\"4\"></body></html>";
        return Texto;
    }
    public static String Dpad = "+x"; // +x, -x, y+, y-
    static int PosicionFruta[][] = new int[2][1];
    static boolean INICIO = true;
    static boolean INICIORELOJ = false;
    static int FrutaRandomInicial[] = new int[2];
    static double MultiplicadorDificultad;
    public static String ReporteInicial = "<h1><center>Práctica 2 | Reporte de resultados   <br>	</center></h1>\n"
            + "<p><b>Alumno: </b>Luis Daniel Castellanos Betancourt<br><b>Carnet: </b> 202103105<br><b>Sección: </b>F<br></p>\n"
            + "<h2><center>*************Reporte de resultados*************<br>	</center></h2>";
    public static String ReporteParaArchivo;
    public static String DifEnString;
            

    public PantallaJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reloj = new javax.swing.JLabel();
        PantallaPrincipal = new javax.swing.JLabel();
        py = new javax.swing.JButton();
        mx = new javax.swing.JButton();
        my = new javax.swing.JButton();
        px = new javax.swing.JButton();
        ComboDificultad = new javax.swing.JComboBox<>();
        BotonIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelIntervalo = new javax.swing.JLabel();
        LabelTamano = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CULEBRITA!");

        Reloj.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        Reloj.setText("00:00:00");

        PantallaPrincipal.setBackground(new java.awt.Color(102, 255, 102));
        PantallaPrincipal.setFont(new java.awt.Font("Source Serif Pro Light", 0, 18)); // NOI18N
        PantallaPrincipal.setAlignmentX(4.0F);
        PantallaPrincipal.setAlignmentY(0.0F);
        PantallaPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        py.setText("w");
        py.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyActionPerformed(evt);
            }
        });
        py.setEnabled(false);

        mx.setText("a");
        mx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mxActionPerformed(evt);
            }
        });
        mx.setEnabled(false);

        my.setText("s");
        my.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myActionPerformed(evt);
            }
        });
        my.setEnabled(false);

        px.setText("d");
        px.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pxActionPerformed(evt);
            }
        });
        px.setEnabled(false);

        ComboDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Medio", "Difícil" }));

        BotonIniciar.setText("INICIAR");
        BotonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarActionPerformed(evt);
            }
        });

        jLabel1.setText("Intervalo:");

        jLabel2.setText("Tamaño: ");

        LabelIntervalo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelIntervalo.setText("0");

        LabelTamano.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelTamano.setText("0");

        jLabel5.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel5.setText("CULEBRITA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(151, 151, 151)
                                        .addComponent(ComboDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonIniciar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addComponent(mx, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LabelTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(LabelIntervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(my, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(px, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(py, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(Reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Reloj)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(LabelIntervalo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(py))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(LabelTamano))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mx)
                            .addComponent(my)
                            .addComponent(px))
                        .addGap(49, 143, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyActionPerformed
        // TODO add your handling code here:
        while (INICIO) {
            System.out.println("INICIA PARTIDA");
            Reloj Reloj = new Reloj();
            HiloCulebra Culebra = new HiloCulebra();

            Culebra.start();
            INICIO = false;
            INICIORELOJ = true;
            Reloj.start();
            BotonIniciar.setEnabled(false);
        }
        Movimientos=Movimientos+ "Arriba, <br>" ;
        Dpad = "+y";
    }//GEN-LAST:event_pyActionPerformed

    private void mxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mxActionPerformed
        // TODO add your handling code here:
        while (INICIO) {
            System.out.println("INICIA PARTIDA");
            Reloj Reloj = new Reloj();
            HiloCulebra Culebra = new HiloCulebra();

            Culebra.start();
            INICIO = false;
            INICIORELOJ = true;
            Reloj.start();
            BotonIniciar.setEnabled(false);
        }
        Movimientos=Movimientos+ "Izquierda, <br>" ;
        Dpad = "-x";
    }//GEN-LAST:event_mxActionPerformed

    private void myActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myActionPerformed
        // TODO add your handling code here:
        while (INICIO) {
            System.out.println("INICIA PARTIDA");
            Reloj Reloj = new Reloj();
            HiloCulebra Culebra = new HiloCulebra();

            Culebra.start();
            INICIO = false;
            INICIORELOJ = true;
            Reloj.start();
            BotonIniciar.setEnabled(false);
        }
        Movimientos=Movimientos+ "Abajo, <br>" ;
        Dpad = "-y";
    }//GEN-LAST:event_myActionPerformed

    private void pxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pxActionPerformed
        // TODO add your handling code here:
        while (INICIO) {
            System.out.println("INICIA PARTIDA");
            Reloj Reloj = new Reloj();
            HiloCulebra Culebra = new HiloCulebra();

            Culebra.start();
            INICIO = false;
            INICIORELOJ = true;
            Reloj.start();
            BotonIniciar.setEnabled(false);
        }
        Movimientos=Movimientos+ "Derecha, <br>" ;
        Dpad = "+x";
    }//GEN-LAST:event_pxActionPerformed

    private void BotonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < 10; i++) { // llena inicialmente pantalla de vacios
            for (int j = 0; j < 10; j++) {
                PantallaJuego.DatosPantallaCulebra[i][j] = "□";
            }
        }
        PantallaJuego.PosicionFruta[0][0] = PantallaJuego.FrutaRandomInicial[0];//Posicion inicial Fruta X, inicia todas las variables iniciales
        PantallaJuego.PosicionFruta[1][0] = PantallaJuego.FrutaRandomInicial[1];//Posicion inicial Fruta Y 
        PantallaJuego.FrutaRandomInicial[0] = (int) (Math.random() * (9 - 0 + 1) + 0);
        PantallaJuego.FrutaRandomInicial[1] = (int) (Math.random() * (9 - 0 + 1) + 0);
        PantallaJuego.DatosPantallaCulebra[PantallaJuego.FrutaRandomInicial[0]][PantallaJuego.FrutaRandomInicial[1]] = "<font style=\"color:red;\">▣</font>";//caracter posicion inicial fruta
        PantallaJuego.DatosPantallaCulebra[4][4] = "<font style=\"color:green;\">■</font>";
        
        if (ComboDificultad.getSelectedIndex() == 0) { //Revisa que dificultad se selecciono
            MultiplicadorDificultad = 0.03;
            System.out.println("entro a facil");
            DifEnString="Fácil";
        } else if (ComboDificultad.getSelectedIndex() == 1) {
            MultiplicadorDificultad = 0.06;
            DifEnString="Medio";
            System.out.println("entro a medio");
        } else if (ComboDificultad.getSelectedIndex() == 2) {
            System.out.println("entro a dificil");
            DifEnString="Dificil";
            MultiplicadorDificultad = 0.09;
        }
        my.setEnabled(true); //Habilita botones
        mx.setEnabled(true);
        py.setEnabled(true);
        px.setEnabled(true);

        PantallaPrincipal.setText(TextoParaPantalla(DatosPantallaCulebra)); //Imprime en pantalla los parametros iniciales
        LabelIntervalo.setText("1000");
        LabelTamano.setText("1");
        Reloj.setText("00:00:00");


    }//GEN-LAST:event_BotonIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BotonIniciar;
    private javax.swing.JComboBox<String> ComboDificultad;
    public static javax.swing.JLabel LabelIntervalo;
    public static javax.swing.JLabel LabelTamano;
    public static javax.swing.JLabel PantallaPrincipal;
    private static javax.swing.JLabel Reloj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JButton mx;
    public static javax.swing.JButton my;
    public static javax.swing.JButton px;
    public static javax.swing.JButton py;
    // End of variables declaration//GEN-END:variables
}
